name: flutter_base_ui
description: A base UI package.
version: 0.0.1
author: Yuzo
homepage: https://github.com/Yuzopro

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # 异步处理（flutter_base_ui）
  rxdart: any
  # 下拉加载（flutter_base_ui）
  pull_to_refresh: any
  # 浏览器（flutter_base_ui）
  webview_flutter: any
  # 图片浏览（flutter_base_ui）
  photo_view: any
  # 打开系统浏览器（flutter_base_ui）
  url_launcher: any
  # loading状态
  flutter_spinkit: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_common_util:
    path: ../flutter_common_util
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
